### PR TITLE
remove openxlsx package

### PR DESCRIPTION
**Pull request by ljwoodley**
```
survey_project_read <- redcap_read_oneshot(redcap_uri = Sys.getenv("URI"),
                               token = Sys.getenv("SURVEY_TOKEN"))$data %>%
  filter(!is.na(research_encounter_id)) %>%
  mutate(igg_antibodies = NA)
```

You can set `igg_antibodies` to NA for testing

### CODE REVIEW

**Comment by ChemiKyle** [comment]
`openxlsx` is also used in `load_results_into_survey_project.R` and `load_results_into_pky_projects.R` so adjusting the Dockerfile will break those scripts.

**Comment by ljwoodley** [comment]
Oh yep. `load_results_into_pky_projects.R` is no longer in use and there isn't any plans to update `load_results_into_survey_project.R` on tools4. Maybe we can leave openxlsx in the docker file but remove it when building the container on tools4? I'm really not sure what's the best route.

Also, we can simply cancel this PR and there'll be no issues. It depends on if removing openxlsx is really a must do.

**Comment by ChemiKyle** [comment]
I seem to be the only person who has issues with `openxlsx`, as I've said before my issue is that during `docker build` the library doesn't compile. Since the Excel format has legitimate uses (i.e. preventing its "smart" features from altering fields) I'm not sure accommodating my system's issue is always the best way forward.

On that note, what docker version are you on?

**Comment by ljwoodley** [comment]
This PR has been cancelled.

**Pull request closed without merging**
